import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Lexend, Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import Footer from "@/components/Footer";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const lexand = Lexend({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en_IN" className={cn("font-sans", geist.variable)}>
      <body className={`bg-[#111111] ${lexand.className}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
