import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Lexend } from "next/font/google";

const lexand = Lexend({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en_IN">
      <body className={`bg-black ${lexand.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
